version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 99
  assignees:
  - nosan
  ignore:
  - dependency-name: org.springframework.boot:spring-boot-starter-data-cassandra
    versions:
    - ">= 2.3.a, < 2.4"
  - dependency-name: org.springframework.boot:spring-boot-starter-test
    versions:
    - ">= 2.3.a, < 2.4"
